services:
  # File logger A: simulates app logs in namespace "fnlgr-demo"
  file-logger-a:
    container_name: file-logger-a
    image: ubuntu:24.04
    working_dir: /app
    volumes:
      - ./file-logger:/app:ro
      - ./file-logger-logs:/var/log/sample
    command: ["bash", "/app/app.sh"]
    environment:
      LOG_FILE: /var/log/sample/app-a.log
      LOG_INTERVAL_SEC: "5"
      LOG_LEVELS: "INFO DEBUG ERROR"
      K8S_NAMESPACE: "fnlgr-demo"
  # File logger B: simulates app logs in namespace "statsvc-env5"
  file-logger-b:
    container_name: file-logger-b
    image: ubuntu:24.04
    working_dir: /app
    volumes:
      - ./file-logger:/app:ro
      - ./file-logger-logs:/var/log/sample
    command: ["bash", "/app/app.sh"]
    environment:
      LOG_FILE: /var/log/sample/app-b.log
      LOG_INTERVAL_SEC: "5"
      LOG_LEVELS: "INFO DEBUG ERROR"
      K8S_NAMESPACE: "statsvc-env5"
  # Fluentd service: tails both log files, filters by namespace/level, and writes merged output
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluentd
    volumes:
    - ./file-logger-logs:/fluentd/log/files/ # input: raw logs generated by file-loggers
    - ./fluentd-configurations:/fluentd/etc/ # configuration: fluent.conf and related files
    - ./fluentd-filtered-logs:/output/ # output: merged, filtered logs
    logging:
      driver: "local"
