services:
  # This app writes logs to a local file
  file-logger:
    container_name: file-logger
    image: ubuntu:24.04
    working_dir: /app
    volumes:
      - ./file-logger:/app:ro
      - ./file-logger-logs:/var/log/sample
    command: ["bash", "/app/app.sh"]
    environment:
      LOG_FILE: /var/log/sample/app.log
      LOG_INTERVAL_SEC: "5"
      LOG_LEVELS: "INFO DEBUG ERROR"
  # This is the Fluentd service that collects and filter logs
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluentd
    volumes:
    - ./file-logger-logs:/fluentd/log/files/ # logs to read from a file
    - ./fluentd-configurations:/fluentd/etc/
    - ./fluentd-filtered-logs:/output/ # Fluentd will collect filtered logs and store it here
    logging:
      driver: "local"
