apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        Off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    # ensure parsing first, then lua filter
    @INCLUDE filter-resultcode.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
      Name              tail
      Tag               kube.*
      Path              /var/log/containers/*.log
      multiline.parser  docker, cri
      Mem_Buf_Limit     5MB
      Skip_Long_Lines   On
      Refresh_Interval  10
      
  filter-kubernetes.conf: |
    [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On
      Use_Kubelet false

    # Parse Apache logs into structured fields
    [FILTER]
      Name       parser
      Match      kube.*
      Key_Name   log
      Parser     apache

  filter-resultcode.conf: |
    [FILTER]
      Name        lua
      Match       kube.*
      script      resultCodeFilter.lua
      call        filter_by_annotation

  output-elasticsearch.conf: |
    [OUTPUT]
      Name            es
      Match           *
      Host            elasticsearch.demo-elastic.svc.cluster.local
      Port            9200
      HTTP_User       elastic
      HTTP_Passwd     ${ELASTICSEARCH_PASSWORD}
      Index           fluentbit
      Retry_Limit     False
      Buffer_Size     False
  
  parsers.conf: |
    [PARSER]
      Name   apache
      Format regex
      Regex  ^(?<client_ip>\d+\.\d+\.\d+\.\d+) - - \[(?<time>[^\]]*)\] "(?<method>[A-Z]+) (?<path>[^ ]*) HTTP/(?<http_version>[^"]+)" (?<status>[0-9]+) (?<size>[0-9]+)
      Time_Key   time
      Time_Format %d/%b/%Y:%H:%M:%S %z

  resultCodeFilter.lua: |
    function filter_by_annotation(tag, ts, record)
        local status = record["status"]
        local filter = nil
        local k8s = record["kubernetes"]

        if k8s ~= nil and k8s["annotations"] ~= nil then
            filter = k8s["annotations"]["customFilter/resultCode"]
        end

        if status ~= nil and filter ~= nil then
            for code in string.gmatch(filter, '([^,]+)') do
                if tostring(status) == code then
                    return 0, record  -- keep log
                end
            end
        end
        return -1, record  -- drop if not matching
    end
